feat: Новый функционал: Добавление/удаление друзей, вывод общих друзе…
IliaStarikov/java-filmorate pull request #6
Opened 2024-02-23 01:52 UTC by IliaStarikov

Добавление/удаление друзей, вывод общих друзей. Добавление/удаление лайков, а так же вывод популярных фильмов. Рефакторинг. SPRINT10 HW

2024-02-23 07:13 UTC, ErkinKasymaliev requested changes
привет, оставил комменты

2024-02-23 07:13 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/advice/ErrorHandler.java
> +    }
тут кажется еще нужно отлавливать INTERNAL_SERVER_ERROR

2024-02-23 07:13 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    FilmService filmService;
private final

2024-02-23 07:13 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +@AllArgsConstructor
@ReqArgsConstructor

2024-02-23 07:13 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    UserService userService;
private final

2024-02-23 07:13 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +@AllArgsConstructor
@ReqArgsConstructor

2024-02-23 07:13 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private Set<Long> likes = new HashSet<>();
id всегда держите вначале

2024-02-23 07:13 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    private Set<Long> friends = new HashSet<>();
id всегда держите вначале

2024-02-23 07:13 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +        return new HashSet<>(friends);
просто return friends

2024-02-23 07:13 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +        return new HashSet<>(likes);
return likes

2024-02-23 07:13 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    FilmStorage filmStorage;
private final

2024-02-23 07:13 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +@AllArgsConstructor
id всегда держите вначале

2024-02-23 07:13 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    UserStorage userStorage;
private final

2024-02-23 07:13 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    public User put(User user) {
update

2024-03-04 03:35 UTC, johnskyi commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +@AllArgsConstructor
обрати пожалуйста внимание на этот комментарий

2024-03-26 19:24 UTC, merged